Repository Open-Study-College/osc, pull requests merged in 2022-12, with the labels that each got.

#558 Docs/Add documentation to storybook
  packages/osc-academic-hub/app/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
  packages/osc-ecommerce/app/components/ThemeSwitcher/ThemeSwitcher.stories.tsx
  packages/osc-ui/src/components/Avatar/Avatar.stories.tsx
  packages/osc-ui/src/components/Badge/Badge.stories.tsx
  packages/osc-ui/src/components/Breadcrumb/Breadcrumb.stories.tsx
  packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
  packages/osc-ui/src/components/List/List.stories.tsx
  packages/osc-ui/src/components/Modal/Modal.stories.tsx
  packages/osc-ui/src/components/Switch/Switch.stories.tsx
  packages/osc-ui/src/components/Tabs/Tabs.stories.tsx
  packages/osc-ui/src/components/Tag/Tag.stories.tsx
  packages/osc-ui/src/components/Trustpilot/Trustpilot.stories.tsx
Labels: documentation

#567 Feature/buttons component
  package-lock.json
  packages/osc-ecommerce/app/components/Module.tsx
  packages/osc-ecommerce/app/models/sanity.server.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/content.ts
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-studio/package-lock.json
  packages/osc-studio/schemas/objects/module/button.ts
  packages/osc-studio/schemas/objects/module/buttons.ts
  packages/osc-studio/schemas/objects/module/content.ts
  packages/osc-studio/schemas/schema.ts
  packages/osc-ui/src/components/Badge/Badge.tsx
  packages/osc-ui/src/components/Button/Button.spec.tsx
  packages/osc-ui/src/components/Button/Button.stories.tsx
  packages/osc-ui/src/components/Button/Button.tsx
  packages/osc-ui/src/components/Button/button.scss
  packages/osc-ui/src/components/Content/Content.spec.tsx
  packages/osc-ui/src/components/Content/Content.stories.tsx
  packages/osc-ui/src/components/Content/Content.tsx
  packages/osc-ui/src/components/Content/textContent.ts
  packages/osc-ui/src/hooks/useModifier.ts
  packages/osc-ui/src/hooks/useVariant.ts
  packages/osc-ui/src/types.ts
Labels: ui, studio, ecommerce

#632 Bugfix/Alerts component test
  packages/osc-ui/src/components/Alert/Alert.spec.tsx
Labels: bug

#638 Refactor/downgrade sanity cli
  packages/osc-studio/package.json
Labels: bug

#639 Feature/css reset
  .stylelintignore
  packages/osc-ui/src/components/Modal/modal.scss
  packages/osc-ui/src/styles/generic/_normalize.scss
  packages/osc-ui/src/styles/generic/_reset.scss
  packages/osc-ui/src/styles/main.scss
Labels: Styles

#631 Refactor/carousel from embla to keen
  package-lock.json
  packages/osc-studio/schemas/objects/module/carousel.ts
  packages/osc-ui/package.json
  packages/osc-ui/src/components/Carousel/Carousel.spec.tsx
  packages/osc-ui/src/components/Carousel/Carousel.stories.tsx
  packages/osc-ui/src/components/Carousel/Carousel.tsx
  packages/osc-ui/src/components/Carousel/CarouselArrows.tsx
  packages/osc-ui/src/components/Carousel/CarouselDots.tsx
  packages/osc-ui/src/components/Carousel/carousel.scss
  packages/osc-ui/src/utils/rem.spec.ts
  packages/osc-ui/src/utils/rem.ts
  packages/osc-ui/tsconfig.json
Labels: ui, studio

#642 Bugfix/common-js rollup plugin / duplicate packages in workspaces
  package-lock.json
  package.json
  packages/osc-ui/package.json
  packages/osc-ui/rollup.config.js
Labels: bug
