Repository Open-Study-College/osc, pull requests merged in 2023-06, with the labels that each got.

#866 Feature/product e2e
  package-lock.json
  package.json
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductForm.tsx
  packages/osc-ecommerce/e2e/navbar.spec.ts
  packages/osc-ecommerce/e2e/product.spec.ts
  packages/osc-ecommerce/package.json
Labels: codeball:needs-careful-review

#933 Feature/cart
  packages/osc-ecommerce/app/components/Cart/AlreadyInCartMessage.tsx
  packages/osc-ecommerce/app/components/Cart/CartCardItem.tsx
  packages/osc-ecommerce/app/components/Cart/CartTotal.tsx
  packages/osc-ecommerce/app/components/Cart/EmptyCartMessage.tsx
  packages/osc-ecommerce/app/components/Cart/Layout.tsx
  packages/osc-ecommerce/app/components/Cart/LineItem.tsx
  packages/osc-ecommerce/app/components/Forms/AddToCart/AddToCart.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductForm.tsx
  packages/osc-ecommerce/app/constants.ts
  packages/osc-ecommerce/app/queries/sanity/cart.ts
  packages/osc-ecommerce/app/queries/sanity/lineItemData.ts
  packages/osc-ecommerce/app/queries/shopify/cart.ts
  packages/osc-ecommerce/app/queries/shopify/product.ts
  packages/osc-ecommerce/app/root.tsx
  packages/osc-ecommerce/app/routes/cart.tsx
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/app/types/shopify.ts
  packages/osc-ecommerce/app/utils/cart.helpers.ts
  packages/osc-ecommerce/app/utils/getPageType.ts
  packages/osc-ecommerce/app/utils/storefront.helpers.spec.ts
  packages/osc-ecommerce/app/utils/storefront.helpers.ts
  packages/osc-studio/schemas/singletons/settings.ts
  packages/osc-ui/src/index.tsx
  packages/osc-ui/src/styles/utilities/_util.scss
Labels: codeball:needs-careful-review

#934 Feature/remove from cart
  packages/osc-ecommerce/app/components/Cart/CartCardItem.tsx
  packages/osc-ecommerce/app/components/Cart/CartTotal.tsx
  packages/osc-ecommerce/app/components/Cart/Layout.tsx
  packages/osc-ecommerce/app/components/Cart/LineItem.tsx
  packages/osc-ecommerce/app/components/Cart/RemovedFromCartMessage.tsx
  packages/osc-ecommerce/app/components/ErrorAlert/ErrorAlert.tsx
  packages/osc-ecommerce/app/components/Forms/CartActions/AddToCart.tsx
  packages/osc-ecommerce/app/components/Forms/CartActions/RemoveFromCart.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductForm.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/product-form.scss
  packages/osc-ecommerce/app/queries/shopify/cart.ts
  packages/osc-ecommerce/app/routes/cart.tsx
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/app/utils/cart.helpers.ts
  packages/osc-ecommerce/app/utils/getDifferenceBetweenArrays.spec.ts
  packages/osc-ecommerce/app/utils/getDifferenceBetweenArrays.ts
  packages/osc-ecommerce/app/utils/storefront.helpers.ts
  packages/osc-ui/src/styles/utilities/_anim.scss
Labels: codeball:needs-careful-review

#935 Feature/update cart item
  packages/osc-ecommerce/app/components/Cart/CartCardItem.tsx
  packages/osc-ecommerce/app/components/Cart/Layout.tsx
  packages/osc-ecommerce/app/queries/shopify/cart.ts
  packages/osc-ecommerce/app/queries/shopify/product.ts
  packages/osc-ecommerce/app/routes/cart.tsx
  packages/osc-ecommerce/app/utils/cart.helpers.ts
Labels: codeball:needs-careful-review

#939 Feature/discounts
  packages/osc-ecommerce/app/components/Cart/CartCardItem.tsx
  packages/osc-ecommerce/app/components/Cart/CartTotal.tsx
  packages/osc-ecommerce/app/components/Cart/DiscountBox/DiscountBox.tsx
  packages/osc-ecommerce/app/components/Cart/DiscountBox/discount-box.scss
  packages/osc-ecommerce/app/components/Cart/Layout.tsx
  packages/osc-ecommerce/app/components/Cart/LineItem.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductForm.tsx
  packages/osc-ecommerce/app/components/Price/Price.tsx
  packages/osc-ecommerce/app/queries/shopify/cart.ts
  packages/osc-ecommerce/app/routes/cart.tsx
  packages/osc-ecommerce/app/utils/cart.helpers.ts
  packages/osc-ui/src/components/LineItem/line-item.scss
  packages/osc-ui/src/components/TextInput/TextInput.tsx
Labels: codeball:needs-careful-review

#940 Bugfix/text input
  packages/osc-ui/src/components/TextInput/TextInput.spec.tsx
  packages/osc-ui/src/components/TextInput/TextInput.stories.tsx
  packages/osc-ui/src/components/TextInput/TextInput.tsx
Labels: bug, codeball:needs-careful-review

#937 Feature/row
  package-lock.json
  packages/osc-ecommerce/app/components/Accordion/Accordion.tsx
  packages/osc-ecommerce/app/components/Cards/Cards.spec.tsx
  packages/osc-ecommerce/app/components/Cards/Cards.tsx
  packages/osc-ecommerce/app/components/Cards/mockCardData.ts
  packages/osc-ecommerce/app/components/Carousel/Carousel.tsx
  packages/osc-ecommerce/app/components/Content/Content.tsx
  packages/osc-ecommerce/app/components/ContentMedia/ContentMedia.tsx
  packages/osc-ecommerce/app/components/ContentMedia/mockContentMediaData.tsx
  packages/osc-ecommerce/app/components/Forms/Forms.tsx
  packages/osc-ecommerce/app/components/Forms/FormsModule.tsx
  packages/osc-ecommerce/app/components/Hero/mockHeroData.tsx
  packages/osc-ecommerce/app/components/Image/Image.tsx
  packages/osc-ecommerce/app/components/Module.tsx
  packages/osc-ecommerce/app/components/RecommendedProducts/RecommendedProducts.spec.tsx
  packages/osc-ecommerce/app/components/RecommendedProducts/RecommendedProducts.tsx
  packages/osc-ecommerce/app/components/Row.tsx
  packages/osc-ecommerce/app/components/Tabs/Tabs.spec.tsx
  packages/osc-ecommerce/app/components/Tabs/Tabs.tsx
  packages/osc-ecommerce/app/components/Tabs/mockTabData.ts
  packages/osc-ecommerce/app/components/TextGrid/TextGrid.tsx
  packages/osc-ecommerce/app/components/VideoPlayer/VideoPlayer.tsx
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/accordion.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/card.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/carousel.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/content.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/contentMedia.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/forms.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/images.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/recommendedProducts.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/rowSettings.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/tabs.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/textGrid.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/video.ts
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/package.json
  packages/osc-studio/schemas/objects/module/accordion.ts
  packages/osc-studio/schemas/objects/module/cards.ts
  packages/osc-studio/schemas/objects/module/carousel.ts
  packages/osc-studio/schemas/objects/module/content.ts
  packages/osc-studio/schemas/objects/module/contentMedia.ts
  packages/osc-studio/schemas/objects/module/forms.ts
  packages/osc-studio/schemas/objects/module/images.tsx
  packages/osc-studio/schemas/objects/module/recommendedProducts.ts
  packages/osc-studio/schemas/objects/module/tabs.ts
  packages/osc-studio/schemas/objects/module/textGrid.ts
  packages/osc-studio/schemas/objects/module/video.tsx
  packages/osc-studio/schemas/objects/rowSettings.ts
  packages/osc-studio/schemas/schema.ts
  packages/osc-ui/src/components/Content/Content.spec.tsx
  packages/osc-ui/src/components/Content/Content.stories.tsx
  packages/osc-ui/src/components/Content/Content.tsx
  packages/osc-ui/src/components/Content/textContent.ts
  packages/osc-ui/src/components/Hero/Hero.stories.tsx
  packages/osc-ui/src/components/Hero/hero.scss
  packages/osc-ui/src/styles/components/_forms.scss
  packages/osc-ui/src/styles/objects/_row.scss
  packages/osc-ui/src/types.ts
Labels: codeball:needs-careful-review

#941 Feature/cart buyer
  packages/osc-ecommerce/app/queries/shopify/cart.ts
  packages/osc-ecommerce/app/routes/cart.tsx
  packages/osc-ecommerce/app/utils/cart.helpers.ts
Labels: codeball:needs-careful-review

#942 Feature/user signup
  README.md
  packages/osc-api-auth/.env.example
  packages/osc-api-auth/src/resolvers/resolver.ts
  packages/osc-api-auth/src/schemas/schema.ts
  packages/osc-api-auth/src/server/permissions.ts
  packages/osc-api-auth/src/server/rules.ts
  packages/osc-api-auth/src/types/arguments.ts
  packages/osc-api-auth/src/types/environment.ts
  packages/osc-api-auth/src/types/functions.ts
  packages/osc-api-auth/src/types/interfaces.ts
  packages/osc-api-auth/src/utils/account.ts
  packages/osc-api-auth/src/utils/token.ts
  packages/osc-api-gateway/src/server/index.ts
  packages/osc-api/course/index.ts
  packages/osc-api/course/types.ts
  packages/osc-api/emails/index.ts
  packages/osc-api/emails/types.ts
  packages/osc-api/index.ts
  packages/osc-api/package.json
  packages/osc-api/user/index.ts
  packages/osc-api/user/types.ts
  packages/osc-api/utils/index.ts
  packages/osc-api/utils/types.ts
  prisma/schema.prisma
Labels: codeball:needs-careful-review

#943 Feature/algolia instantsearch
  .env.sample
  packages/osc-ecommerce/app/components/Cards/CollectionCard.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Components/ItemCounter.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Components/SearchBox.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/CollectionCards.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Configure.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hit.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hits.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/NoResults/NoResults.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/NoResults/NoResultsBoundary.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Refinements/ClearRefinements.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Refinements/RefinementList.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Refinements/RefinementSlider.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Refinements/SortBy.tsx
  packages/osc-ecommerce/app/components/InstantSearch/data.ts
  packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
  packages/osc-ecommerce/app/components/InstantSearch/types.ts
  packages/osc-ecommerce/app/components/InstantSearch/utils/getRefinementWidget.tsx
  packages/osc-ecommerce/app/lib/sanity/getClient.ts
  packages/osc-ecommerce/app/queries/sanity/collection.ts
  packages/osc-ecommerce/app/routes/search.tsx
  packages/osc-ecommerce/app/routes/search/index.tsx
  packages/osc-ecommerce/package.json
  packages/osc-ecommerce/remix.config.js
  packages/osc-ui/package.json
  packages/osc-ui/src/components/Accordion/Accordion.tsx
  packages/osc-ui/src/components/Checkbox/Checkbox.tsx
  packages/osc-ui/src/components/Checkbox/checkbox.scss
  packages/osc-ui/src/components/Label/Label.tsx
  packages/osc-ui/src/components/Select/Select.tsx
  packages/osc-ui/src/components/Select/select.scss
  packages/osc-ui/src/components/Slider/Slider.tsx
  packages/osc-ui/src/components/Slider/slider.scss
  packages/osc-ui/src/components/TextInput/TextInput.tsx
  packages/osc-ui/src/index.tsx
  packages/osc-ui/src/styles/objects/_container.scss
Labels: codeball:needs-careful-review

#872 Refactor/workflows
  .dockerignore
  .github/actions/deployment/action.yml
  .github/actions/dockerBuild/action.yml
  .github/actions/movePackageToRoot/action.yml
  .github/actions/readAndLogAppNameAndBranch/action.yml
  .github/actions/setupBuild/action.yml
  .github/workflows/chromatic.yml
  .github/workflows/deploy-preview-app.yml
  .github/workflows/deploy-production-app.yml
  .github/workflows/destroy-preview-app.yml
  .github/workflows/osc-academic-hub-deploy.yml
  .github/workflows/osc-academic-hub-destroy-apps.yml
  .github/workflows/osc-academic-hub-pr-branches.yml
  .github/workflows/osc-academic-hub.yml
  .github/workflows/osc-api.yml
  .github/workflows/osc-ecommerce-deploy.yml
  .github/workflows/osc-ecommerce-destroy-apps.yml
  .github/workflows/osc-ecommerce-pr-branches.yml
  .github/workflows/osc-ecommerce.yml
  .github/workflows/osc-studio-deploy.yml
  .github/workflows/osc-studio-destroy-apps.yml
  .github/workflows/osc-studio-pr-branches.yml
  .github/workflows/osc-studio.yml
  .github/workflows/planetscale-create-db-branch.yml
  .github/workflows/planetscale-create-deployment-request.yml
  .github/workflows/tests.yml
  Dockerfiles/Dockerfile
  Dockerfiles/Dockerfile.pr
  Dockerfiles/Dockerfile.studio
  Dockerfiles/__tmp__Dockerfile.db-pr
  README.md
  docker-compose.yml
  package-lock.json
  package.json
  packages/osc-academic-hub/Dockerfile
  packages/osc-academic-hub/Dockerfile.pr
  packages/osc-academic-hub/fly-pr.toml
  packages/osc-academic-hub/fly.toml
  packages/osc-ecommerce/Dockerfile
  packages/osc-ecommerce/Dockerfile.pr
  packages/osc-ecommerce/app/components/Footer/Footer.tsx
  packages/osc-ecommerce/app/root.tsx
  packages/osc-ecommerce/fly-pr.toml
  packages/osc-ecommerce/fly.toml
  packages/osc-studio/Dockerfile
  packages/osc-studio/Dockerfile.pr
  packages/osc-studio/desk/blog.ts
  packages/osc-studio/desk/home.ts
  packages/osc-studio/desk/index.ts
  packages/osc-studio/desk/products.ts
  packages/osc-studio/fly-pr.toml
  packages/osc-studio/package.json
  packages/osc-studio/sanity.config.ts
  workflow-scripts/cancel.sh
Labels: build:osc-studio, build:osc-ecommerce, codeball:needs-careful-review

#954 Feature/checkbox size sm
  packages/osc-ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/osc-ui/src/components/Checkbox/Checkbox.tsx
  packages/osc-ui/src/components/Checkbox/checkbox.scss
  packages/osc-ui/src/components/Label/Label.tsx
  packages/osc-ui/src/components/Label/label.scss
Labels: codeball:needs-careful-review

#983 Feature/forgot password email
  packages/osc-api-auth/.env.example
  packages/osc-api-auth/src/resolvers/resolver.ts
  packages/osc-api-auth/src/schemas/schema.ts
  packages/osc-api-auth/src/types/arguments.ts
  packages/osc-api-auth/src/types/environment.ts
  packages/osc-api-auth/src/types/functions.ts
  packages/osc-api-auth/src/utils/account.ts
  packages/osc-api/emails/index.ts
  packages/osc-api/emails/types.ts
Labels: codeball:needs-careful-review

#1033 Feature/update colour names in sanity
  packages/osc-studio/components/inputs/ColorPicker.tsx
  packages/osc-studio/components/inputs/ColorPickerRestricted.tsx
  packages/osc-studio/constants.js
  packages/osc-studio/constants.ts
Labels: build:osc-studio, codeball:needs-careful-review

#1034 Feature/product cart pending states
  packages/osc-ecommerce/app/components/Cart/CartTotal.tsx
  packages/osc-ecommerce/app/components/Cart/DiscountBox/DiscountBox.tsx
  packages/osc-ecommerce/app/components/Cart/Layout.tsx
  packages/osc-ecommerce/app/components/Cart/LineItem.tsx
  packages/osc-ecommerce/app/components/Forms/CartActions/RemoveFromCart.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductForm.tsx
  packages/osc-ui/src/components/Button/Button.spec.tsx
  packages/osc-ui/src/components/Button/Button.tsx
  packages/osc-ui/src/components/Button/button.scss
  packages/osc-ui/src/styles/utilities/_anim.scss
  packages/osc-ui/src/styles/utilities/_util.scss
Labels: build:osc-ecommerce, codeball:needs-careful-review

#1128 Feature/sticky header
  packages/osc-ecommerce/app/components/Header/Header.tsx
  packages/osc-ui/src/components/Drawer/drawer.scss
  packages/osc-ui/src/components/Header/Header.spec.tsx
  packages/osc-ui/src/components/Header/Header.tsx
  packages/osc-ui/src/components/Header/header.scss
  packages/osc-ui/src/hooks/useScroll.ts
Labels: build:osc-ecommerce, codeball:needs-careful-review

#1133 Feature/progress component
  package-lock.json
  packages/osc-ui/package.json
  packages/osc-ui/src/components/Progress/Progress.spec.tsx
  packages/osc-ui/src/components/Progress/Progress.stories.tsx
  packages/osc-ui/src/components/Progress/Progress.tsx
  packages/osc-ui/src/components/Progress/progress.scss
Labels: codeball:needs-careful-review

#1134 Feature/pagination component
  package-lock.json
  packages/osc-ui/src/components/Pagination/Pagination.spec.tsx
  packages/osc-ui/src/components/Pagination/Pagination.stories.tsx
  packages/osc-ui/src/components/Pagination/Pagination.tsx
  packages/osc-ui/src/components/Pagination/pagination.scss
Labels: codeball:needs-careful-review

#1136 Feature/add infinite hits to instantsearch
  package-lock.json
  packages/osc-design-tokens/tokens/containers.js
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/Hits/Hits.tsx
  packages/osc-ecommerce/app/components/InstantSearch/Widgets/InfiniteHits.tsx
  packages/osc-ecommerce/app/components/InstantSearch/instant-search.scss
  packages/osc-ecommerce/app/routes/search.tsx
  packages/osc-ui/src/index.tsx
  packages/osc-ui/src/styles/objects/_container.scss
  packages/osc-ui/src/styles/settings/_containers.scss
  packages/osc-ui/src/styles/settings/_tokens.scss
Labels: build:osc-ecommerce, codeball:needs-careful-review

#1138 Feature/algolia instantsearch e2e tests v2
  packages/osc-ecommerce/e2e/search.spec.ts
  packages/osc-ecommerce/playwright.config.ts
Labels: codeball:needs-careful-review

#1164 Feature/system preferences
  .gitignore
  package-lock.json
  package.json
  packages/osc-api-gateway/package.json
  packages/osc-api-gateway/src/server/index.ts
  packages/osc-api-gateway/src/types/environment.ts
  packages/osc-api-settings/.env.example
  packages/osc-api-settings/.gitignore
  packages/osc-api-settings/package.json
  packages/osc-api-settings/src/index.ts
  packages/osc-api-settings/src/resolvers/resolver.ts
  packages/osc-api-settings/src/schemas/schema.ts
  packages/osc-api-settings/src/server/index.ts
  packages/osc-api-settings/src/server/permissions.ts
  packages/osc-api-settings/src/server/rules.ts
  packages/osc-api-settings/src/types/arguments.ts
  packages/osc-api-settings/src/types/environment.ts
  packages/osc-api-settings/src/types/functions.ts
  packages/osc-api-settings/src/types/interfaces.ts
  packages/osc-api-settings/src/utils/preferences.ts
  packages/osc-api-settings/tsconfig.json
  packages/osc-api/index.ts
  packages/osc-api/settings/index.ts
  packages/osc-api/settings/types.ts
  prisma/schema.prisma
Labels: build:osc-academic-hub, codeball:needs-careful-review
