Repository Open-Study-College/osc, pull requests merged in 2023-05, with the labels that each got.

#822 Feature/add sanity preview kit
  .env.sample
  .github/actions/dockerBuild/action.yml
  .github/workflows/osc-ecommerce-deploy.yml
  .github/workflows/osc-ecommerce-pr-branches.yml
  Dockerfiles/Dockerfile
  Dockerfiles/Dockerfile.pr
  README.md
  package-lock.json
  packages/osc-ecommerce/app/components/PageContent.tsx
  packages/osc-ecommerce/app/components/PagePreview.tsx
  packages/osc-ecommerce/app/components/Preview.tsx
  packages/osc-ecommerce/app/components/PreviewBanner.tsx
  packages/osc-ecommerce/app/hooks/usePreviewSubscription.ts
  packages/osc-ecommerce/app/lib/sanity/config.ts
  packages/osc-ecommerce/app/models/sanity.server.ts
  packages/osc-ecommerce/app/previewSession.server.ts
  packages/osc-ecommerce/app/queries/sanity/blog.ts
  packages/osc-ecommerce/app/queries/sanity/collection.ts
  packages/osc-ecommerce/app/queries/sanity/home.ts
  packages/osc-ecommerce/app/queries/sanity/page.ts
  packages/osc-ecommerce/app/queries/sanity/post.ts
  packages/osc-ecommerce/app/queries/sanity/product.ts
  packages/osc-ecommerce/app/routes/$slug.tsx
  packages/osc-ecommerce/app/routes/blog/$slug.tsx
  packages/osc-ecommerce/app/routes/blog/index.tsx
  packages/osc-ecommerce/app/routes/collections/$slug.tsx
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ecommerce/app/routes/index.tsx
  packages/osc-ecommerce/app/routes/resources/preview.ts
  packages/osc-ecommerce/app/routes/robots[.]txt.ts
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/package.json
  packages/osc-ecommerce/remix.env.d.ts
  packages/osc-studio/utils/resolveProductionUrl.ts
Labels: studio, ecommerce, codeball:needs-careful-review

#853 Feature/css image transformations
  packages/osc-ecommerce/app/routes/cart.tsx
  packages/osc-ecommerce/app/routes/collections/$slug.tsx
  packages/osc-ecommerce/app/routes/collections/index.tsx
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ecommerce/app/routes/graphiql.tsx
  packages/osc-ecommerce/app/utils/cart.helpers.ts
  packages/osc-ecommerce/package.json
  packages/osc-ecommerce/remix.env.d.ts
  packages/osc-ecommerce/server.ts
  packages/osc-ui/src/components/CalloutBanner/callout-banner.scss
  packages/osc-ui/src/components/Card/card.scss
  packages/osc-ui/src/components/Hero/hero.scss
  packages/osc-ui/src/components/Image/Image.spec.tsx
  packages/osc-ui/src/components/Image/Image.stories.tsx
  packages/osc-ui/src/components/Image/Image.tsx
  packages/osc-ui/src/components/Image/utils.tsx
  packages/osc-ui/src/components/VideoPlayer/video-player.scss
  packages/osc-ui/src/styles/objects/_img.scss
Labels: ui, codeball:needs-careful-review

#849 Feature/product form drawer
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductForm.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/ProductFormDrawer.tsx
  packages/osc-ecommerce/app/components/Forms/ProductForm/product-form.scss
  packages/osc-ecommerce/app/root.tsx
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ui/src/components/Button/Button.stories.tsx
  packages/osc-ui/src/components/Button/button.scss
  packages/osc-ui/src/components/Drawer/Drawer.tsx
  packages/osc-ui/src/components/Drawer/drawer.scss
  packages/osc-ui/src/index.tsx
  packages/osc-ui/src/styles/utilities/_util.scss
Labels: ecommerce, codeball:needs-careful-review

#859 Bugfix/product page
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
Labels: bug

#852 Bugfix/accordion modifier styles
  packages/osc-ui/src/components/Accordion/Accordion.spec.tsx
  packages/osc-ui/src/components/Accordion/Accordion.stories.tsx
  packages/osc-ui/src/components/Accordion/Accordion.tsx
  packages/osc-ui/src/components/Accordion/accordion.scss
Labels: bug, ui, codeball:needs-careful-review

#863 feat: add remix routes for awards and create Sanity query
  packages/osc-ecommerce/app/constants.ts
  packages/osc-ecommerce/app/lib/sanity/config.ts
  packages/osc-ecommerce/app/queries/sanity/award.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/buildUrls.ts
  packages/osc-ecommerce/app/routes/awards/$slug.tsx
  packages/osc-ecommerce/app/routes/awards/index.tsx
  packages/osc-ecommerce/app/utils/getPageType.ts
  packages/osc-studio/constants.js
  packages/osc-studio/desk/awardingBodyPages.ts
  packages/osc-studio/schemas/documents/awardingBodyPages.tsx
  packages/osc-studio/utils/resolveProductionUrl.ts
Labels: codeball:needs-careful-review

#865 Feature/add forms to content media
  packages/osc-ecommerce/app/components/Cards/Cards.tsx
  packages/osc-ecommerce/app/components/ContentMedia/ContentMedia.tsx
  packages/osc-ecommerce/app/components/Forms/Forms.tsx
  packages/osc-ecommerce/app/components/Module.tsx
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/contentMedia.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/forms.ts
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/app/utils/hubspot.helpers.ts
  packages/osc-studio/schemas/objects/contentMediaSlide.ts
Labels: codeball:needs-careful-review

#854 Feature/sanity image controls
  packages/osc-ecommerce/app/components/Cards/BlogCard.tsx
  packages/osc-ecommerce/app/components/Cards/CollectionCard.tsx
  packages/osc-ecommerce/app/components/Cards/SimpleCard.tsx
  packages/osc-ecommerce/app/components/Carousel/Carousel.tsx
  packages/osc-ecommerce/app/components/ContentMedia/ContentMedia.tsx
  packages/osc-ecommerce/app/components/Hero/Hero.tsx
  packages/osc-ecommerce/app/components/Module.tsx
  packages/osc-ecommerce/app/components/VideoPlayer/VideoPlayer.tsx
  packages/osc-ecommerce/app/queries/sanity/collection.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/card.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/images.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/video.ts
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-studio/schemas/documents/collection.tsx
  packages/osc-studio/schemas/documents/post.ts
  packages/osc-studio/schemas/objects/module/cardPost.ts
  packages/osc-studio/schemas/objects/module/image.tsx
  packages/osc-studio/schemas/objects/theme.ts
  packages/osc-studio/schemas/schema.ts
  packages/osc-ui/src/components/Card/card.scss
Labels: build:osc-studio, build:osc-ecommerce, codeball:needs-careful-review

#864 Feature/recommended products
  packages/osc-ecommerce/app/components/Cards/Cards.tsx
  packages/osc-ecommerce/app/components/Cards/CourseCard.tsx
  packages/osc-ecommerce/app/components/Module.tsx
  packages/osc-ecommerce/app/components/RecommendedProducts/RecommendedProducts.spec.tsx
  packages/osc-ecommerce/app/components/RecommendedProducts/RecommendedProducts.tsx
  packages/osc-ecommerce/app/components/RecommendedProducts/mockProductData.tsx
  packages/osc-ecommerce/app/hooks/useRecommendedProducts.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/childModules.ts
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/recommendedProducts.ts
  packages/osc-ecommerce/app/queries/shopify/product.ts
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-studio/constants.js
  packages/osc-studio/schemas/documents/product.tsx
  packages/osc-studio/schemas/objects/carouselSettings.ts
  packages/osc-studio/schemas/objects/module/recommendedProducts.ts
  packages/osc-studio/schemas/schema.ts
Labels: codeball:needs-careful-review

#928 Bugfix/getHubspotForms causing pages without modules to crash
  packages/osc-ecommerce/app/utils/hubspot.helpers.ts
Labels: bug, codeball:needs-careful-review

#835 Feature/flourishes
  packages/osc-ui/src/components/Card/CollectionCard.stories.tsx
  packages/osc-ui/src/components/Card/card.scss
  packages/osc-ui/src/components/Flourishes/Flourish.stories.tsx
  packages/osc-ui/src/components/Flourishes/Flourishes.spec.tsx
  packages/osc-ui/src/components/Flourishes/Flourishes.stories.tsx
  packages/osc-ui/src/components/Flourishes/Flourishes.tsx
  packages/osc-ui/src/components/Flourishes/flourish.scss
  packages/osc-ui/src/components/Flourishes/patterns/_patterns.scss
  packages/osc-ui/src/components/Flourishes/patterns/collectionPrimary.ts
  packages/osc-ui/src/components/Flourishes/patterns/collectionQuaternary.ts
  packages/osc-ui/src/components/Flourishes/patterns/collectionQuinary.ts
  packages/osc-ui/src/components/Flourishes/patterns/collectionSecondary.ts
  packages/osc-ui/src/components/Flourishes/patterns/collectionTertiary.ts
  packages/osc-ui/src/components/Flourishes/patterns/heroPrimary.ts
  packages/osc-ui/src/components/Flourishes/patterns/heroSecondary.ts
  packages/osc-ui/src/components/Flourishes/patterns/heroTertiary.ts
  packages/osc-ui/src/components/Flourishes/patterns/index.ts
  packages/osc-ui/src/components/Flourishes/patterns/primary.ts
  packages/osc-ui/src/components/Flourishes/patterns/secondary.ts
  packages/osc-ui/src/components/Hero/Hero.stories.tsx
  packages/osc-ui/src/components/Hero/Hero.tsx
  packages/osc-ui/src/components/Hero/hero.scss
  packages/osc-ui/src/types.ts
  packages/osc-ui/src/utils/handleMouseEvents.ts
  packages/osc-ui/src/utils/mergeEventHandlers.ts
  packages/osc-ui/src/utils/throttle.spec.ts
  packages/osc-ui/src/utils/throttle.ts
Labels: ui, codeball:needs-careful-review

#898 Refactor/price component
  packages/osc-ecommerce/app/components/Price/Price.tsx
  packages/osc-ecommerce/app/components/Price/price.scss
  packages/osc-ecommerce/app/root.tsx
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ui/src/components/Card/Card.tsx
  packages/osc-ui/src/components/Card/CourseCard.stories.tsx
  packages/osc-ui/src/components/Price/Price.spec.tsx
  packages/osc-ui/src/components/Price/Price.stories.tsx
  packages/osc-ui/src/components/Price/Price.tsx
  packages/osc-ui/src/components/Price/price.scss
  packages/osc-ui/src/index.tsx
Labels: codeball:needs-careful-review

#840 Feature/add flourishes to hero sanity
  packages/osc-ecommerce/app/components/Hero/Hero.spec.tsx
  packages/osc-ecommerce/app/components/Hero/Hero.tsx
  packages/osc-ecommerce/app/components/Hero/mockHeroData.tsx
  packages/osc-ecommerce/app/components/Module.tsx
  packages/osc-ecommerce/app/queries/sanity/fragments/modules/hero.ts
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/app/utils/remapFlourishObject.ts
  packages/osc-studio/components/inputs/ColorPickerRestricted.tsx
  packages/osc-studio/schemas/objects/flourishes.ts
  packages/osc-studio/schemas/objects/heroSlide.ts
  packages/osc-studio/schemas/schema.ts
  packages/osc-ui/src/index.tsx
Labels: build:osc-studio, build:osc-ecommerce, codeball:needs-careful-review

#841 Feature/add flourishes to product pages
  packages/osc-ecommerce/app/components/Cards/mockCardData.ts
  packages/osc-ecommerce/app/models/sanity.server.ts
  packages/osc-ecommerce/app/queries/sanity/product.ts
  packages/osc-ecommerce/app/queries/shopify/product.ts
  packages/osc-ecommerce/app/root.tsx
  packages/osc-ecommerce/app/routes/courses/$slug.tsx
  packages/osc-ecommerce/app/types/sanity.ts
  packages/osc-ecommerce/app/utils/remapFlourishObject.ts
  packages/osc-studio/schemas/documents/collection.tsx
  packages/osc-studio/schemas/documents/page.ts
  packages/osc-studio/schemas/documents/post.ts
  packages/osc-studio/schemas/objects/flourishes.ts
  packages/osc-studio/schemas/singletons/blog.ts
  packages/osc-studio/schemas/singletons/home.ts
  packages/osc-ui/src/index.tsx
  packages/osc-ui/src/styles/utilities/_util.scss
Labels: build:osc-studio, build:osc-ecommerce, codeball:needs-careful-review

#929 Feature/checkbox size
  packages/osc-ui/src/components/Checkbox/Checkbox.stories.tsx
  packages/osc-ui/src/components/Checkbox/Checkbox.tsx
  packages/osc-ui/src/components/Checkbox/checkbox.scss
  packages/osc-ui/src/components/Label/Label.tsx
  packages/osc-ui/src/components/Label/label.scss
Labels: codeball:needs-careful-review

#930 Feature/callout secondary
  packages/osc-ui/src/components/CalloutBanner/CalloutBanner.stories.tsx
  packages/osc-ui/src/components/CalloutBanner/CalloutBanner.tsx
  packages/osc-ui/src/components/CalloutBanner/callout-banner.scss
  packages/osc-ui/src/components/Content/content.scss
Labels: codeball:needs-careful-review

#907 Feature/cart item card
  packages/osc-ecommerce/app/components/Cards/BioCard.tsx
  packages/osc-ecommerce/app/components/Cards/CollectionCard.tsx
  packages/osc-ecommerce/app/components/Cards/CourseCard.tsx
  packages/osc-ecommerce/app/components/Cards/SimpleCard.tsx
  packages/osc-ui/src/components/Accordion/Accordion.stories.tsx
  packages/osc-ui/src/components/Accordion/Accordion.tsx
  packages/osc-ui/src/components/Accordion/accordion.scss
  packages/osc-ui/src/components/Button/button.scss
  packages/osc-ui/src/components/Card/Card.stories.tsx
  packages/osc-ui/src/components/Card/Card.tsx
  packages/osc-ui/src/components/Card/CartCard.stories.tsx
  packages/osc-ui/src/components/Card/CollectionCard.stories.tsx
  packages/osc-ui/src/components/Card/CourseCard.stories.tsx
  packages/osc-ui/src/components/Card/card.scss
  packages/osc-ui/src/components/Label/Label.tsx
  packages/osc-ui/src/components/Label/label.scss
  packages/osc-ui/src/components/Select/Select.tsx
  packages/osc-ui/src/components/Select/select.scss
  packages/osc-ui/src/styles/utilities/_util.scss
Labels: codeball:needs-careful-review
